exercise_rows = [
('Back Lat Pulldowns', 'back_lat_pulldowns.png', 'Instructions:\n 1. Sit facing the machine with the thighs positioned under the pads, grasping the bar with a wide (wider than shoulder width) overhand grip.\n 2. As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso and head forward (lean your torso slightly forward, keeping your neck and back straight).\n 3. Think of an imaginary line from the center of the bar down to the back of your neck.\n 4. Inhale and, pull the bar down to the back of the neck, bringing the elbows alongside the body.\n 5. Exhale at the end of the movement.\n 6. Hold the contraction for a moment, then slowly return the bar all the way back to the starting position.', 'Strenght'),
('Butterfly', 'butterfly.png', 'Instructions:\n 1. Sit on the machine with your back flat on the pad.\n 2. Take hold of the handles. Tip: Your upper arms should be positioned parallel to the floor; adjust the machine accordingly. This will be your starting position.\n 3. Push the handles together slowly as you squeeze your chest in the middle. Breathe out during this part of the motion and hold the contraction for a second.\n 4. Return back to the starting position slowly as you inhale until your chest muscles are fully stretched.\n 5. Repeat for the recommended amount of repetitions.', 'Strenght'),
('Chest Press', 'chest_press.png', 'Instructions:\n 1. Sit upright with your back supported by the back pad.\n 2. Hold the fixed handles at chest height; adjust the seat, if needed\n 3. Press the handles forward until your arms are fully extended.\n 4. Slowly return to the starting position.', 'Strenght'),
('Front Lat Pulldowns', 'front_lat_pulldowns.png', 'Instructions:\n 1. Sit facing away from machine with your knees locked under the roller pads.\n 2. Grip the lat bar with your hands slightly wider than shoulder width, with your palms facing forward.\n 3. Lean back slightly, and pull the bar down slowly until it touches your upper chest area.\n 4. Slowly return to the starting position.', 'Strenght'),
('Front Lat Pullover', 'front_lat_pullover.png', 'Instructions:\n 1. Attach the chain to the high pulley, and then attach the straight bar to the end of the chain.\n 2. Grab the straight bar with an overhand grip.\n 3. Keep your arms straight and pull down.\n 4. Return slowly.', 'Strenght'),
('Glute Kick', 'glute_kick.png', 'Instructions:\n 1. Hook a leather ankle cuff to a low cable pulley and then attach the cuff to your ankle.\n 2. Face the weight stack from a distance of about two feet, grasping the steel frame for support.\n 3. While keeping your knees and hips bent slightly and your abs tight, contract your glutes to slowly \"kick\" the working leg back in a semicircular arc as high as it will comfortably go as you breathe out.\n 4. Repeat for the recommended amount of repetitions.\n, 5. Switch legs and repeat the movement for the other side.', 'Strenght'),
('Inner Thigh', 'inner_thigh.png', 'Instructions:\n 1. Attach the padded cuff to the lower pulley.\n 2. Stand sideways to the machine.\n 3. Attach the cuff to the leg closest to the machine.\n 4. Slowly scissor your leg across your body while keeping your body straight.\n 5. Slowly return to the starting position.', 'Strenght'),
('Leg curl', 'leg_curl.png', 'Instructions:\n 1. Stand facing the machine, and adjust the upper roller pads to hit just above your knees.\n 2. Hook one foot under lower roller pad, and grip the press arm for balance.\n 3. Curl your leg upward, and hold your position momentarily.\n 4. Slowly return to the starting position', 'Strenght'),
('Leg extension', 'leg_extension.png', 'Instructions:\n 1. Adjust the seat so that the pivot of the left extension/leg curl arms lines up with the pivot point of your knees.\n 2. Adjust back pad angle, if needed\n 3. Hook your legs over the upper roller pads and your feet under the lowest roller pads.\n 4. Extend your legs forward, and hold your position momentarily.\n 5. Slowly return to starting position.\n', 'Strenght'),
('Outer Thigh', 'outer_thigh.png', 'Instructions:\n 1. Attach the padded cuff to the lower pulley.\n 2. Stand sideways to the machine.\n 3. Attach the cuff to the leg furthest from the machine.\n 4. While keeping your leg straight and positioned slightly in front of your body, lift your leg outward and upward as far as possible. Keep your body straight, and lead with your heel.\n 5. Slowly return to the starting position.', 'Strenght'),
('Overhead Biceps Curl', 'overhead_biceps_curl.png', 'Instructions:\n 1. Attach the straight bar to the high pulley.\n 2. Sit facing the machine and lock your knees under the knee hold-down pads.\n 3. Grab the straight bar with an underhand grip.\n 4. Concentrate on keeping your upper arm stationary while curling the straight bar behind your head.\n 5. Return slowly', 'Strenght'),
('Seated cable row', 'seated_cable_row.png', 'Instructions:\n 1. Stand facing the machine, and adjust the upper roller pads to hit just above your knees.\n 2. Hook one foot under lower roller pad, and grip the press arm for balance.\n 3. Curl your leg upward, and hold your position momentarily.\n 4. Slowly return to the starting position', 'Strenght'),
('Triceps Extension From High Pulley', 'triceps_extension_from_high_pulley.png', 'Instructions:\n 1. Attach the straight bar to the high pulley.\n 2. Sit in the seat leaning slightly forward and grab the straight bar with an overhand grip.\n 3. Try to hold your upper arm locked into a horizontal position while extending your lower arm at the elbow.\n 4. Return slowly.', 'Strenght'),
('Triceps pushdown', 'triceps_pushdown.png', 'Instructions:\n 1. Attach the easy curl bar to the high pulley.\n 2. Stand facing towards the machine.\n 3. Grip the bar with your hands 4 to 6 inch apart, palms facing forward.\n 4. Bring the bar to chest height. Keep your arms tight against your body, and push the bar down slowly.\n 5. Slowly return to the starting position.', 'Strenght')
]

user_rows = [

]
