USE muscle2;

--INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('', 'Instructions:\n ', '', 'Strenght')

INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Chest Press', 'Instructions:\n 1. Sit upright with your back supported by the back pad.\n 2. Hold the fixed handles at chest height; adjust the seat, if needed\n 3. Press the handles forward until your arms are fully extended.\n 4. Slowly return to the starting position.', 'chest_press.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Front Lat Pulldowns', 'Instructions:\n 1. Sit facing away from machine with your knees locked under the roller pads.\n 2. Grip the lat bar with your hands slightly wider than shoulder width, with your palms facing forward.\n 3. Lean back slightly, and pull the bar down slowly until it touches your upper chest area.\n 4. Slowly return to the starting position.', 'front_lat_pulldowns.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Leg extension', 'Instructions:\n 1. Adjust the seat so that the pivot of the left extension/leg curl arms lines up with the pivot point of your knees.\n 2. Adjust back pad angle, if needed\n 3. Hook your legs over the upper roller pads and your feet under the lowest roller pads.\n 4. Extend your legs forward, and hold your position momentarily.\n 5. Slowly return to starting position.\n', 'leg_extension.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Triceps pushdown', 'Instructions:\n 1. Attach the easy curl bar to the high pulley.\n 2. Stand facing towards the machine.\n 3. Grip the bar with your hands 4 to 6 inch apart, palms facing forward.\n 4. Bring the bar to chest height. Keep your arms tight against your body, and push the bar down slowly.\n 5. Slowly return to the starting position.', 'triceps_pushdown.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Leg curl', 'Instructions:\n 1. Stand facing the machine, and adjust the upper roller pads to hit just above your knees.\n 2. Hook one foot under lower roller pad, and grip the press arm for balance.\n 3. Curl your leg upward, and hold your position momentarily.\n 4. Slowly return to the starting position', 'leg_curl.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Seated cable row', 'Instructions:\n 1. Stand facing the machine, and adjust the upper roller pads to hit just above your knees.\n 2. Hook one foot under lower roller pad, and grip the press arm for balance.\n 3. Curl your leg upward, and hold your position momentarily.\n 4. Slowly return to the starting position', 'seated_cable_row.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Front Lat Pullover', 'Instructions:\n 1. Attach the chain to the high pulley, and then attach the straight bar to the end of the chain.\n 2. Grab the straight bar with an overhand grip.\n 3. Keep your arms straight and pull down.\n 4. Return slowly.', 'front_lat_pullover.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Overhead Biceps Curl', 'Instructions:\n 1. Attach the straight bar to the high pulley.\n 2. Sit facing the machine and lock your knees under the knee hold-down pads.\n 3. Grab the straight bar with an underhand grip.\n 4. Concentrate on keeping your upper arm stationary while curling the straight bar behind your head.\n 5. Return slowly', 'overhead_biceps_curl.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Triceps Extension From High Pulley', 'Instructions:\n 1. Attach the straight bar to the high pulley.\n 2. Sit in the seat leaning slightly forward and grab the straight bar with an overhand grip.\n 3. Try to hold your upper arm locked into a horizontal position while extending your lower arm at the elbow.\n 4. Return slowly.', 'triceps_extension_from_high_pulley.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Butterfly', 'Instructions:\n 1. Sit on the machine with your back flat on the pad.\n 2. Take hold of the handles. Tip: Your upper arms should be positioned parallel to the floor; adjust the machine accordingly. This will be your starting position.\n 3. Push the handles together slowly as you squeeze your chest in the middle. Breathe out during this part of the motion and hold the contraction for a second.\n 4. Return back to the starting position slowly as you inhale until your chest muscles are fully stretched.\n 5. Repeat for the recommended amount of repetitions.', 'butterfly.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Back Lat Pulldowns', 'Instructions:\n 1. Sit facing the machine with the thighs positioned under the pads, grasping the bar with a wide (wider than shoulder width) overhand grip.\n 2. As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso and head forward (lean your torso slightly forward, keeping your neck and back straight).\n 3. Think of an imaginary line from the center of the bar down to the back of your neck.\n 4. Inhale and, pull the bar down to the back of the neck, bringing the elbows alongside the body.\n 5. Exhale at the end of the movement.\n 6. Hold the contraction for a moment, then slowly return the bar all the way back to the starting position.', 'back_lat_pulldowns.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Inner Thigh', 'Instructions:\n 1. Attach the padded cuff to the lower pulley.\n 2. Stand sideways to the machine.\n 3. Attach the cuff to the leg closest to the machine.\n 4. Slowly scissor your leg across your body while keeping your body straight.\n 5. Slowly return to the starting position.', 'inner_thigh.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Outer Thigh', 'Instructions:\n 1. Attach the padded cuff to the lower pulley.\n 2. Stand sideways to the machine.\n 3. Attach the cuff to the leg furthest from the machine.\n 4. While keeping your leg straight and positioned slightly in front of your body, lift your leg outward and upward as far as possible. Keep your body straight, and lead with your heel.\n 5. Slowly return to the starting position.', 'outer_thigh.png', 'Strenght');
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Glute Kick', 'Instructions:\n 1. Hook a leather ankle cuff to a low cable pulley and then attach the cuff to your ankle.\n 2. Face the weight stack from a distance of about two feet, grasping the steel frame for support.\n 3. While keeping your knees and hips bent slightly and your abs tight, contract your glutes to slowly "kick" the working leg back in a semicircular arc as high as it will comfortably go as you breathe out.\n 4. Repeat for the recommended amount of repetitions.\n 5. Switch legs and repeat the movement for the other side.', 'glute_kick.png', 'Strenght');
--new ones
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Reverse Triceps Pushdown', 'Instructions:\n 1. Stand facing the machine and use the single-grip attachment on the highest pulley, with an underhand grip (i.e. thumbs facing outward). \n 2. Keeping your elbows at your body\'s sides, press the weight downward, while exhaling throughout the movement. If desired, you may self-spot with your free hand. \n 3. Slowly allow the weight to rise until your forearms are parallel to the ground, inhaling throughout the negative motion. \n 4. Repeat steps 2-3 for as many sets as are desired.', 'reverse_triceps_pushdown.png', 'Strenght')
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Reverse Lat Pull-Downs', 'Instructions:\n 1. Use the bar attachment on the high pulley.\n 2. Adjust the thigh pad height so that, when seated, by pressing slightly with your toes, your legs will remain firmly planted on the ground, thereby keeping your body from moving. \n 3. Face the machine, sit, and position your thighs beneath the pads. \n 4. Grasp the bar in underhand position (i.e. palms facing away from one another) at shoulder-width or less. \n 5. Pull the bar to your upper chest or nipple line, keeping your body upright and puffing out your chest, exhaling throughout the movement. Your elbows should be pointing forward. \n 6. Slowly lower the weight to the starting position, letting your arms fully extend (without letting your elbow joint slam as your arms straighten), inhaling throughout the negative motion. \n 7. Repeat steps 4-5 for as many repetitions as are desired.', 'reverse_lat_pull-downs.png', 'Strenght')
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Biceps Curl', 'Instructions:\n 1. Use the lowest pulley.\n 2. Stand or sit with your arms at your sides. \n 3. Grasp the desired attachment. \n 4. Curl the weight upward briefly pausing and squeezing at the top (full flexion), exhaling throughout the movement. \n 5. Slowly lower the weight to the starting position, inhaling throughout the entire negative (downward) motion. \n 6. Repeat steps 3-4 for as many sets as are desired. (Sets should generally fall between 3 to 6 with 6-12 repetitions).', 'biceps_curl.png', 'Strenght')
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('One-Arm Side Cable Laterals', 'Instructions:\n 1. Set the pulley to the lowest setting.\n 2. Secure a single-hand attachment to the cable machine.\n 3. Stand an arms-length away, position the body directly to the side of the weight stack (the feet should be perpendicular to the weight stack).\n 4. Grab the attachment with an overhand (pronated grip), stand up straight while keeping the knees slightly bent and the feet shoulder with apart.\n 5. With the attachment held at your side and a slight bend in the elbow, raise the attachment up and away until it becomes level with your head, inhaling as you pull it up.\n 6. Slowly lower the attachment down, exhaling throughout the motion. \n  7. Rotate the body 180 degrees to work the other side and repeat steps 5-6.', 'one-arm_side_cable_laterals.png', 'Strenght')
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('External Arm Rotations', 'Instructions:\n 1. Use the lowest pulley and ensure that a single-handed attachment is attached to the cable.\n 2. Stand at a 90 degree angle to the cable apparatus, far enough so that you can hold the pulley at level with your waist. \n 3. Grasp the single cable attachment in front of your body and stand upright. Your elbow should be bent and at your side and the attachment should be resting against your abdomen. \n 4. Rotate your arm externally while keeping your elbow at your side until your arm can rotate no further, then extend your arm fully (at which time your elbow will move away from your side), squeeze the shoulder and outer back muscles briefly, all the while exhaling throughout. \n 5. Slowly allow the arm to return to the starting position, inhaling throughout the movement. \n 6. Repeat steps 4-5 for as many repetitions as are desired.', 'external_arm_rotations.png', 'Strenght')
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Front Arm Raises', 'Instructions:\n 1. Use the pulley of the lowest setting.\n 2. Secure a single-hand or straight-bar attachment to the cable machine. \n 3. Position the body to face directly at the weight stack. \n 4. Grab the attachment with an overhand (pronated) grip, stand up straight while keeping the knees slightly bent and the feet shoulder with apart. \n 5. With a slight bend in the elbow(s), raise the attachment up and away until it becomes eye level, inhaling as you pull it up. \n 6. Slowly lower the attachment down, exhaling throughout the motion. \n 7. Repeat steps 5-6. If using the single-hand attachment, switch hands after a set is completed.', 'front_arm_raises.png', 'Strenght')
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('One-Arm Cross Cable Laterals', 'Instructions:\n 1. Use the lowest pulley and secure the single-grip attachment.\n 2. With the attachment to the left of the body, grab it with the right hand reaching around in front of the body. \n 3. Attachment in hand, take a few steps away from the machine to put a bit of tension on the line. \n 4. Keeping a slight bend in the elbow, pull the attachment out and away from the body, arcing upward until the arm is directly to side of the body with the hand about eye level. Inhale throughout this motion. \n 5. Slowly return the weight to its starting position while exhaling. \n 6. Repeat steps 5-6', 'one-arm_cross_cable_laterals.png', 'Strenght')
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('Upright Rows', 'Instructions:\n 1. Grasp the desired cable attachment (straight or easy curl bar) with an overhand grip at a width of at least six inches or wider and (carefully) stand so that the bar is resting against your thighs.\n 2. Tighten your abdominals (and keep them tight throughout), pull the weight upward to just beneath your chin (with your elbows pointing outward to the sides and raised as high as possible/comfortable), while exhaling throughout the movement. \n 3. Slowly lower the bar to the starting position, while exhaling throughout the movement. \n 4. Repeat steps 2-3 for as many repetitions as are desired.', 'upright_rows.png', 'Strenght')
INSERT INTO EXERCISE (Name, Description, Image, Kind) Values ('One-Arm Cable Crunches', 'Instructions:\n 1. Use the high pulley.\n 2. Attach a single rope, single handle, or nothing at all if it does not cause pain to grip the attachment loop with a bare hand.\n 3. Commit a firm grasp onto the desired attachment.\n 4. While holding the attachment, drop to a kneeling position where the feet are behind the legs forming a 90 degree angle at the knees. \n 5. Bring the attachment in close to the body with the elbow significantly bent (the hand should be directly in front of pectoral). \n 6. With the arm and elbow locked, pull the cable down and toward the knee opposite of the hand holding it (envision driving the elbow holding the attachment to the opposite knee\'s cap). \n 7. Hold this crunched position for 2-3 seconds. \n 8. Resist the cable as it pulls back up. \n 9. Repeat steps 6-8 then switch hands to execute one-arm cable crunches on the other side', 'one-arm_cable_crunches.png', 'Strenght')


